Updated getContext() to catch Throwable instead of Exception when attempting to create a secure ldap context.  Handles case where Error is thrown - for example NoClassDefFoundError.